# Generated by Django 6.0.1 on 2026-03-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['name'], 'verbose_name': 'project list', 'verbose_name_plural': 'project lists'},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diyprojects.projectcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='materials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='steps',
            field=models.TextField(),
        ),
    ]
