# Generated by Django 5.2.11 on 2026-05-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0005_project_creator_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
