# Generated by Django 5.2.10 on 2026-05-06 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_role_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField()),
                ('sypnopsis', models.TextField()),
                ('publication_year', models.IntegerField()),
                ('borrow_availability', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['-publication_year'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_date', models.DateField(auto_now_add=True)),
                ('bookmark_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_book', to='bookclub.book')),
                ('bookmark_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarker', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'bookmark',
                'verbose_name_plural': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnonReviewer', models.TextField()),
                ('bookreview_title', models.CharField(max_length=255)),
                ('bookreview_comment', models.TextField()),
                ('UserReviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='accounts.profile')),
                ('bookreview_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_books', to='bookclub.book')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField()),
                ('book_borrowdate', models.DateField(auto_now_add=True)),
                ('borrow_returndate', models.DateField()),
                ('borrow_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to='bookclub.book')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'borrowed',
                'verbose_name_plural': 'multiple_borrowed',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookclub.genre'),
        ),
    ]
