# Generated by Django 5.2.10 on 2026-05-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_alter_profile_id'),
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_book', to='bookclub.book'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarker', to='accounts.profile'),
        ),
    ]
