# Generated by Django 5.2.10 on 2026-05-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_role'),
        ('bookclub', '0002_alter_bookmark_bookmark_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_books', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='AnonReviewer',
            field=models.TextField(default='Text'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_borrowdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
