# Generated by Django 5.2.11 on 2026-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_id_alter_commission_people_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commissiontype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
