# Generated by Django 6.0.2 on 2026-05-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('commissions', '0004_commission_status_commission_type_job_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
