# Generated by Django 6.0.2 on 2026-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_commission_maker_jobapplication_applicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['status', '-manpower_required', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-applied_on']},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1_OPEN', 'Open'), ('2_FULL', 'Full')], default='1_OPEN'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('1_PEND', 'Pending'), ('2_ACPT', 'Accepted'), ('3_RJCT', 'Rejected')], default='1_PEND'),
        ),
    ]
