# Generated by Django 6.0.1 on 2026-05-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('localevents', '0004_event_event_capacity_event_event_image_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(null=True, to='accounts.profile'),
        ),
    ]
