# Generated by Django 6.0.1 on 2026-05-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('localevents', '0005_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='new_registrant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='user_registrant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_registrants', to='accounts.profile'),
        ),
    ]
