# Generated by Django 6.0.1 on 2026-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0006_eventsignup_new_registrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
